<font size = 4 face = "黑体">

![捕获异常处理](https://img-blog.csdnimg.cn/20200202153342841.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQzODA4NzAw,size_16,color_FFFFFF,t_70)

try语句块中放可能出现异常的语句 </br>
catch语句的作用是捕获异常 </br>
finally语句块作用是终止 </br>


1. try：

try语句指定了一段代码，该段代码就是异常捕获并处理的范围。在执行过程中，当任意一条语句产生异常时，就会跳过该条语句中后面的代码。代码中可能会产生并抛出一种或几种类型的异常对象，它后面的catch语句要分别对这些异常做相应的处理。

一个try语句必须带有至少一个catch语句块或一个finally语句块 。

注意事项

当异常处理的代码执行结束以后，不会回到try语句去执行尚未执行的代码。

2. catch：

n-每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。

n-常用方法，这些方法均继承自Throwable类 。

u-toString ()方法，显示异常的类名和产生异常的原因

u-getMessage()方法，只显示产生异常的原因，但不显示类名。

u-printStackTrace()方法，用来跟踪异常事件发生时堆栈的内容。

n-catch捕获异常时的捕获顺序：

u-如果异常类之间有继承关系，在顺序安排上需注意。越是顶层的类，越放在下面，再不然就直接把多余的catch省略掉。 也就是先捕获子类异常再捕获父类异常。

2. finally：

n-有些语句，不管是否发生了异常，都必须要执行，那么就可以把这样的语句放到finally语句块中。

n-通常在finally中关闭程序块已打开的资源，比如：关闭文件流、释放数据库连接等。

try-catch-finally语句块的执行过程：

try-catch-finally程序块的执行流程以及执行结果比较复杂。

基本执行过程如下：

程序首先执行可能发生异常的try语句块。如果try语句没有出现异常则执行完后跳至finally语句块执行;如果try语句出现异常，则中断执行并根据发生的异常类型跳至相应的catch语句块执行处理。catch语句块可以有多个，分别捕获不同类型的异常。catch语句块执行完后程序会继续执行finally语句块。finally语句是可选的，如果有的话，则不管是否发生异常，finally语句都会被执行。

注意事项

1. 即使try和catch块中存在return语句，finally语句也会执行。是在执行完finally语句后再通过return退出。

2. finally语句块只有一种情况是不会执行的，那就是在执行finally之前遇到了System.exit(0)结束程序运行。


```java
package yzy.exception;

//继承关系 FileNotFoundException -> IOException -> Exception -> Throwable -> Object
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

public class testTryCatch {
	public static void main(String[] args) {
		//声明文件流对象
		FileReader reader = null;
		try {
			reader = new FileReader("D:/testTryCatch.txt");
			char c1 = (char)reader.read();  //reader返回第一个字符(以int类型返回)
			System.out.println(c1);
		}catch(FileNotFoundException e){  //或者Exception也可以  //捕获FileReader的异常
			e.printStackTrace();  //从栈追溯异常
		} catch (IOException e) {  //捕获reader的异常
			e.printStackTrace();  //打印异常信息
		}finally {  //关闭资源
			try {
				if(reader != null) {  //异常处理
					reader.close();
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		
		/*
		* 注意catch语句子类FileNotFoundException异常应该在父类IOException异常前面,
		* 如果父类IOException异常在子类FileNotFoundException异常前面,
		* 父类IOException的异常既能捕获FileReader异常又能捕获reader的异常
		* 逻辑上FileNotFoundException的catch语句便不会执行,而且编译器也会报错
		* 
		* 
		* 比较偷懒的做法是只用一个Exception捕获所有异常,但是不建议这么做
		 */
	}
}

```


![FileReader继承关系](https://img-blog.csdnimg.cn/20200202160458416.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQzODA4NzAw,size_16,color_FFFFFF,t_70)



</br>

总结重点: </br>

子类异常捕获catch应该在父类异常捕获catch前面





</font>